### ISSUE TITLE
No compatible version found: @tars/rpc@^2.0.0

### ISSUE THREAD

**Issue by wmchan1168** [tars-node/node-agent#3]
after you publish version 2.0.0 of @node-agent on npm.org, I got the problem below.

![image](https://user-images.githubusercontent.com/5230044/41151275-dcfc780c-6b42-11e8-905c-f8e332f5d90d.png)

**Comment by medns** [comment]
Fixed, please try again

**Comment by wmchan1168** [comment]
Ok, thx~
